- backend/build.gradle
- backend/src/main/java/ch/uzh/ifi/imrg/platform/controller/ChatbotTemplateController.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/controller/PatientController.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/controller/TherapistController.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/service/ChatbotTemplateService.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/service/PatientService.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/service/TherapistService.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/utils/JwtUtil.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/utils/PasswordUtil.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/utils/SecurityConfig.java
- frontend/src/@types/resources.d.ts
> 60: therapist password encryption

- frontend/src/api/.openapi-generator/FILES
- frontend/src/generalComponents/Layout.tsx
- frontend/src/hooks/useTypewriter.ts
- frontend/src/pages/chatBotTemplate/ChatBotTemplateEdit.tsx
- frontend/src/utils/formatResponse.tsx
> 238: General Therapist Chatbot

- backend/src/main/java/ch/uzh/ifi/imrg/platform/controller/ChatbotTemplateController.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/rest/dto/input/UpdateChatbotTemplateDTO.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/rest/mapper/ChatbotTemplateMapper.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/service/ChatbotTemplateService.java
> 271: Remove chatbotIcon

- frontend/src/api/.openapi-generator/FILES
- frontend/src/api/apis/chatbot-template-controller-api.ts
- frontend/src/pages/chatBotTemplate/ChatBotTemplateEdit.tsx
> 256: Display Active Chatbot Frontend

- frontend/src/pages/chatBotTemplate/ChatBotTemplateEdit.tsx
> 256: Display Active Chatbot

- frontend/src/utils/api.ts
> 267: Testing of Entire Application for Bugs (Fix Coach Registration + Login)

- backend/src/main/java/ch/uzh/ifi/imrg/platform/service/ChatbotTemplateService.java
> 354: Deactivating Active Chatbot Deactivates All Chatbots

- frontend/src/pages/chatBotTemplate/ChatBotTemplateEdit.tsx
> 355: Add Translations

- frontend/src/generalComponents/Layout.tsx
- frontend/src/pages/chatBotTemplate/ChatBotTemplateEdit.tsx
> 360: Fix Multiple Messages Coach Chatbot

- frontend/public/locales/de.json
- frontend/public/locales/en.json
- frontend/public/locales/ua.json
- frontend/src/@types/resources.d.ts
- frontend/src/pages/meetings/MeetingCreate.tsx
> 341: Meeting Creation Allows Negative Minute Durations

- frontend/public/locales/de.json
- frontend/public/locales/en.json
- frontend/public/locales/ua.json
- frontend/src/@types/resources.d.ts
- frontend/src/pages/meetings/MeetingEditing.tsx
> 342: Meeting Edit Allows End Date Before Start Date

- frontend/public/locales/de.json
- frontend/public/locales/en.json
- frontend/public/locales/ua.json
- frontend/src/@types/resources.d.ts
- frontend/src/pages/exercises/ExerciseDetail.tsx
- frontend/src/pages/meetings/MeetingEditing.tsx
> 345: Exercise Edit Allows End Date Before Start Date

- frontend/src/generalComponents/FileUpload.tsx
- frontend/src/pages/exercises/components/CreateExerciseFileComponent.tsx
> 348: Fix Images Exercise Details

- frontend/src/pages/home/Home.tsx
> Fix: Normal File Uploads Occasionally Trigger Client App Backend Errors

- frontend/src/generalComponents/SpeechRecognitionComponent.tsx
> 343: Transcribe Meeting Produces Duplicate Transcriptions

- backend/src/main/java/ch/uzh/ifi/imrg/platform/entity/Patient.java
- backend/src/main/java/ch/uzh/ifi/imrg/platform/service/TherapistChatbotService.java
> 424: Change the Name of the Therapist Chatbot to Eliza Backend

- frontend/public/locales/de.json
- frontend/public/locales/en.json
- frontend/public/locales/ua.json
- frontend/src/@types/resources.d.ts
- frontend/src/pages/therapistChatbot/TherapistChatbot.tsx
- frontend/src/utils/routes.ts
> 424: Change the Name of the Therapist Chatbot to Eliza

- backend/src/test/java/ch/uzh/ifi/imrg/platform/controller/CounselingPlanPhaseControllerTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/entity/CounselingPlanPhaseTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/mapper/CounselingPlanPhaseMapperTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/service/CounselingPlanPhaseServiceTest.java
> 433: Implement Backend Tests for CounselingPlanPhase

- backend/src/test/java/ch/uzh/ifi/imrg/platform/controller/CounselingPlanPhaseGoalControllerTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/entity/CounselingPlanPhaseGoalTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/output/CounselingPlanPhaseGoalOutputDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/service/CounselingPlanPhaseGoalServiceTest.java
> 434: Implement Backend Tests for CounselingPlanPhaseGoal

- backend/src/test/java/ch/uzh/ifi/imrg/platform/controller/ExerciseComponentControllerTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/entity/ExerciseComponentTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/input/CreateExerciseComponentDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/output/ExerciseComponentOutputDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/service/ExerciseComponentServiceTest.java
> 435: Implement Backend Tests for ExerciseComponent

- backend/src/test/java/ch/uzh/ifi/imrg/platform/controller/MeetingControllerTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/input/CreateMeetingDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/input/UpdateMeetingDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/output/MeetingNoteOutputDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/output/MeetingOutputDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/mapper/MeetingsMapperTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/service/MeetingServiceTest.java
> 438: Implement Backend Tests for Meeting

- backend/src/test/java/ch/uzh/ifi/imrg/platform/controller/PatientControllerTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/entity/PatientTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/input/CreatePatientDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/input/UpdatePatientDetailDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/output/PatientOutputDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/mapper/PatientMapperTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/service/PatientServiceTest.java
> 440: Implement Backend Tests for Patient

- backend/src/test/java/ch/uzh/ifi/imrg/platform/controller/PatientTestControllerTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/service/PatientTestServiceTest.java
> 443: Implement Backend Tests for PatientTest

- backend/src/test/java/ch/uzh/ifi/imrg/platform/controller/TherapistChatbotControllerTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/output/TherapistChatbotOutputDTOTest.java
> 444: Implement Backend Tests for TherapistChatbot

- backend/src/test/java/ch/uzh/ifi/imrg/platform/controller/TherapistDocumentControllerTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/entity/TherapistDocumentTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/dto/output/TherapistDocumentOutputDTOTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/rest/mapper/TherapistDocumentMapperTest.java
- backend/src/test/java/ch/uzh/ifi/imrg/platform/service/TherapistDocumentServiceTest.java
> 446: Implement Backend Tests for TherapistDocument
